# ~/.config/starship.toml

# cyan:    #00FFFF  #00A8A5
# magenta: #FF00CC  #A8006A
# green:   #CCFF00  #73A800
# blue:    #0033FF  #0021A8

'$schema' = 'https://starship.rs/config-schema.json'

add_newline = true

format = """\
[î‚¶](fg:#0033FF)\
$os\
$hostname\
[î‚°](bg:#00A8A5 fg:#0033FF)\
$directory\
[î‚°](bg:#A8006A fg:#00A8A5)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[î‚°](bg:#73A800 fg:#A8006A)\
$kubernetes\
[î‚°](fg:#73A800)
$jobs\
$sudo\
$character"""

[character]
success_symbol = '[ï”](#73A800)'
error_symbol = '[ï”](#A8006A)'

[directory]
format = '[ $path ]($style)'
home_symbol = 'ï“¢'
style = 'bg:#00A8A5'
truncate_to_repo = true
truncation_symbol = 'â€¦/'

[git_branch]
format = '[ $branch]($style)'
symbol = ''
style = 'bg:#A8006A'
truncation_length = 20
truncation_symbol = 'â€¦/'

[git_commit]
format = '[ $tag]($style)'
tag_symbol = ''
style = 'bg:#A8006A'
tag_disabled = false
commit_hash_length = 4

[git_metrics]
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
added_style = 'bold blue'

[git_state]
format = '[ $state($progress_current of $progress_total)]($style)'
style = 'bg:#A8006A'
cherry_pick = 'ğŸ’'

[git_status]
format = '[( $up_to_date$conflicted$untracked$modified$renamed$deleted$stashed$ahead_behind$staged) ]($style)'
style = 'bg:#A8006A'
conflicted = '[ğŸ³](bg:#A8006A fg:#FF8B6B)'
up_to_date = '[î®´](bg:#A8006A fg:#C4FF78)'
untracked = '[ï”©](bg:#A8006A fg:#FF8B6B)'
ahead = '[îª¡${count}](bg:#A8006A fg:white)'
diverged = '[îª¡${ahead_count}îªš${behind_count}](bg:#A8006A fg:white)'
behind = '[îªš${count}](bg:#A8006A fg:white)'
stashed = '[ï’‡](bg:#A8006A fg:white)'
modified = '[î®´](bg:#A8006A fg:#FF8B6B)'
staged = '[+$count](bg:#A8006A fg:white)'
renamed = '[î« ](bg:#A8006A fg:#FF8B6B)'
deleted = '[ï€”](bg:#A8006A fg:#FF8B6B)'

[hostname]
format = '[$hostname ]($style)'
style = 'bg:#0033FF'

[jobs]
format = '[$symbol]($style)'
symbol = '|'
style = '#73A800'

[kubernetes]
disabled = false
format = '[ $symbol$context( \($namespace\)) ]($style)'
symbol = 'âˆ'
style = 'bg:#73A800'

[kubernetes.context_aliases]
'gke.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
'kind-(?P<var_cluster>[\w-]+)' = '$var_cluster'

[os]
disabled = false
format = '[$symbol ]($style)'
style = 'bg:#0033FF'

[os.symbols]
Ubuntu = 'îœº'
Windows  = 'îœ'
